version: '3.7'

services:

  server:
    image: dukdocker/comments_flask:sunday
    volumes:
      - './flask-com:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - APP_SETTINGS=config.ProductionConfig
      - DATABASE_URL=mysql+pymysql://admin:admin@flask-db/comments_prod
    links:
      - flask-db

  flask-db:
    image: dukdocker/comments_db:sunday
    restart: always
    environment:
      - MYSQL_DATABASE=comments_prod
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - flask-db:/var/lib/mysql

volumes:
  flask-db: