version: '3.7'

services:

  server:
    build:
      context: ./flask-api
      dockerfile: Dockerfile
    volumes:
      - './flask-api:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      # - APP_SETTINGS=project.config.DevelopmentConfig
      - APP_SETTINGS=project.config.DevSqliteConfig
      - DATABASE_URL=mysql+pymysql://admin:admin@mysql-db/comments_dev
      # - DATABASE_TEST_URL=mysql+pymysql://admin:admin@mysql-db/comments_test
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: ./flask-api/project/db
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE_PASSWORD=admin