version: '3.7'

services:

  api:
    build:
      context: ./flask-api
      dockerfile: Dockerfile
    volumes:
      - './flask-api:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=mysql://mysql:mysql@comments-db/comments_dev
      - DATABASE_TEST_URL=mysql://mysql:mysql@comments-db/comments_test
    depends_on:
      - comments-db
  
  comments-db:
    build:
      context: ./flask-api/project/db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=@aLong7emporaryPSWD%2019
      - MYSQL_USER='mysql'
